version: '3.8'

volumes:
  pg_data:

services:
  db:
    container_name: fastapi_postgres
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=benchmark
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
